export const SearchActionTypes = {
  SEARCH_POSTS: "@@search/SEARCH_POSTS",
  API_REDUX_LIST_OBSERVABLE: "@@search/API_REDUX_LIST_OBSERVABLE",
  API_REDUX_LIST_THUNK: "@@search/API_REDUX_LIST_THUNK",
  API_REDUX_LIST_SAGA: "@@search/API_REDUX_LIST_SAGA"
};
